INSERT INTO books(Book_Id, Title, Author, Genre) 
VALUES (1, 'The Silent Patient', 'Alex Michaelides', 'Thriller'),
(2, 'Atomic Habits', 'James Clear', 'Self-Help'),
(3, 'The Alchemist', 'Paulo Coelho', 'Fiction'),
(4, 'Rich Dad Poor Dad', 'Robert Kiyosaki', 'Finance'),
(5, 'To Kill a Mockingbird', 'Harper Lee', 'Classic'),
(6, '1984', 'George Orwell', 'Dystopian'),
(7, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Classic'),
(8, 'Sapiens', 'Yuval Noah Harari', 'History'),
(9, 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy'),
(10, 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy'),
(11, 'The Catcher in the Rye', 'J.D. Salinger', 'Classic'),
(12, 'The Lean Startup', 'Eric Ries', 'Business'),
(13, 'Think and Grow Rich', 'Napoleon Hill', 'Self-Help'),
(14, 'The Power of Now', 'Eckhart Tolle', 'Spiritual'),
(15, 'The Subtle Art of Not Giving a F*ck', 'Mark Manson', 'Self-Help'),
(16, 'Gone Girl', 'Gillian Flynn', 'Thriller'),
(17, 'The Girl on the Train', 'Paula Hawkins', 'Thriller'),
(18, 'Becoming', 'Michelle Obama', 'Biography'),
(19, 'Educated', 'Tara Westover', 'Memoir'),
(20, 'The Da Vinci Code', 'Dan Brown', 'Mystery'),
(21, 'Angels and Demons', 'Dan Brown', 'Mystery'),
(22, 'Inferno', 'Dan Brown', 'Mystery'),
(23, 'The Hunger Games', 'Suzanne Collins', 'Dystopian'),
(24, 'Catching Fire', 'Suzanne Collins', 'Dystopian'),
(25, 'Mockingjay', 'Suzanne Collins', 'Dystopian'),
(26, 'Pride and Prejudice', 'Jane Austen', 'Romance'),
(27, 'Me Before You', 'Jojo Moyes', 'Romance'),
(28, 'The Fault in Our Stars', 'John Green', 'Romance'),
(29, 'Dune', 'Frank Herbert', 'Sci-Fi'),
(30, 'Foundation', 'Isaac Asimov', 'Sci-Fi'),
(31, 'Ender''s Game', 'Orson Scott Card', 'Sci-Fi'),
(32, 'The Martian', 'Andy Weir', 'Sci-Fi'),
(33, 'Steve Jobs', 'Walter Isaacson', 'Biography'),
(34, 'Elon Musk', 'Walter Isaacson', 'Biography'),
(35, 'Shoe Dog', 'Phil Knight', 'Business'),
(36, 'Zero to One', 'Peter Thiel', 'Business'),
(37, 'The 4-Hour Workweek', 'Tim Ferriss', 'Business'),
(38, 'Deep Work', 'Cal Newport', 'Productivity'),
(39, 'Clean Code', 'Robert C. Martin', 'Technology'),
(40, 'The Pragmatic Programmer', 'Andrew Hunt', 'Technology'),
(41, 'Introduction to Algorithms', 'Thomas H. Cormen', 'Technology'),
(42, 'Python Crash Course', 'Eric Matthes', 'Technology'),
(43, 'The Shining', 'Stephen King', 'Horror'),
(44, 'It', 'Stephen King', 'Horror'),
(45, 'Dracula', 'Bram Stoker', 'Horror'),
(46, 'Frankenstein', 'Mary Shelley', 'Horror'),
(47, 'The Book Thief', 'Markus Zusak', 'Historical Fiction'),
(48, 'All the Light We Cannot See', 'Anthony Doerr', 'Historical Fiction'),
(49, 'The Nightingale', 'Kristin Hannah', 'Historical Fiction'),
(50, 'Life of Pi', 'Yann Martel', 'Adventure');

SELECT * FROM books