INSERT INTO bookstore (Store_Id, Store_name, City)
VALUES (1, 'T&T Books Johannesburg', 'Johannesburg'),
(2, 'T&T Books Cape Town', 'Cape Town'),
(3, 'T&T Books Durban', 'Durban'),
(4, 'T&T Books Pretoria', 'Pretoria'),
(5, 'T&T Books Port Elizabeth', 'Port Elizabeth'),
(6, 'T&T Books Bloemfontein', 'Bloemfontein'),
(7, 'T&T Books East London', 'East London'),
(8, 'T&T Books Polokwane', 'Polokwane'),
(9, 'T&T Books Nelspruit', 'Nelspruit'),
(10, 'T&T Books Kimberley', 'Kimberley'),
(11, 'T&T Books Rustenburg', 'Rustenburg'),
(12, 'T&T Books George', 'George'),
(13, 'T&T Books Paarl', 'Paarl'),
(14, 'T&T Books Stellenbosch', 'Stellenbosch'),
(15, 'T&T Books Centurion', 'Centurion'),
(16, 'T&T Books Sandton', 'Sandton'),
(17, 'T&T Books Midrand', 'Midrand'),
(18, 'T&T Books Soweto', 'Soweto'),
(19, 'T&T Books Alberton', 'Alberton'),
(20, 'T&T Books Benoni', 'Benoni'),
(21, 'T&T Books Boksburg', 'Boksburg'),
(22, 'T&T Books Germiston', 'Germiston'),
(23, 'T&T Books Krugersdorp', 'Krugersdorp'),
(24, 'T&T Books Witbank', 'Witbank'),
(25, 'T&T Books Secunda', 'Secunda'),
(26, 'T&T Books Richards Bay', 'Richards Bay'),
(27, 'T&T Books Newcastle', 'Newcastle'),
(28, 'T&T Books Pietermaritzburg', 'Pietermaritzburg'),
(29, 'T&T Books Umhlanga', 'Umhlanga'),
(30, 'T&T Books Ballito', 'Ballito'),
(31, 'T&T Books Mossel Bay', 'Mossel Bay'),
(32, 'T&T Books Knysna', 'Knysna'),
(33, 'T&T Books Oudtshoorn', 'Oudtshoorn'),
(34, 'T&T Books Hermanus', 'Hermanus'),
(35, 'T&T Books Somerset West', 'Somerset West'),
(36, 'T&T Books Worcester', 'Worcester'),
(37, 'T&T Books Upington', 'Upington'),
(38, 'T&T Books Mahikeng', 'Mahikeng'),
(39, 'T&T Books Potchefstroom', 'Potchefstroom'),
(40, 'T&T Books Klerksdorp', 'Klerksdorp'),
(41, 'T&T Books Vryburg', 'Vryburg'),
(42, 'T&T Books Thohoyandou', 'Thohoyandou'),
(43, 'T&T Books Giyani', 'Giyani'),
(44, 'T&T Books Tzaneen', 'Tzaneen'),
(45, 'T&T Books Phalaborwa', 'Phalaborwa'),
(46, 'T&T Books Lephalale', 'Lephalale'),
(47, 'T&T Books Mokopane', 'Mokopane'),
(48, 'T&T Books Vereeniging', 'Vereeniging'),
(49, 'T&T Books Vanderbijlpark', 'Vanderbijlpark'),
(50, 'T&T Books Springs', 'Springs');