INSERT INTO customers (Customer_Id, Customer_Name, Age_Group, Gender, Suburb, Race)
VALUES (1, 'Thabo Mokoena', 22, 'Male', 'Soweto', 'Black'),
(2, 'Naledi Khumalo', 30, 'Female', 'Sandton', 'Black'),
(3, 'Pieter van der Merwe', 40, 'Male', 'Pretoria East', 'White'),
(4, 'Ayesha Khan', 28, 'Female', 'Lenasia', 'Indian'),
(5, 'Sipho Dlamini', 24, 'Male', 'Umlazi', 'Black'),
(6, 'Zanele Ndlovu', 32, 'Female', 'KwaMashu', 'Black'),
(7, 'Michael Smith', 50, 'Male', 'Durban North', 'White'),
(8, 'Fatima Patel', 38, 'Female', 'Chatsworth', 'Indian'),
(9, 'Lerato Molefe', 21, 'Female', 'Tembisa', 'Black'),
(10, 'Johan Botha', 60, 'Male', 'Bloemfontein', 'White'),
(11, 'Nomsa Zulu', 29, 'Female', 'Pietermaritzburg', 'Black'),
(12, 'David Cohen', 52, 'Male', 'Sea Point', 'White'),
(13, 'Karabo Seema', 23, 'Male', 'Polokwane', 'Black'),
(14, 'Anika Naidoo', 31, 'Female', 'Phoenix', 'Indian'),
(15, 'Tshepo Sekhoto', 42, 'Male', 'Mamelodi', 'Black'),
(16, 'Chantel Adams', 27, 'Female', 'Mitchells Plain', 'Coloured'),
(17, 'Andre Jacobs', 48, 'Male', 'Stellenbosch', 'Coloured'),
(18, 'Busisiwe Cele', 20, 'Female', 'Richards Bay', 'Black'),
(19, 'Chris Botha', 37, 'Male', 'Centurion', 'White'),
(20, 'Zaid Osman', 33, 'Male', 'Mayfair', 'Indian'),
(21, 'Ayanda Mthembu', 25, 'Female', 'Empangeni', 'Black'),
(22, 'Peter Williams', 58, 'Male', 'Port Elizabeth', 'White'),
(23, 'Nokuthula Sithole', 34, 'Female', 'Katlehong', 'Black'),
(24, 'Ravi Pillay', 41, 'Male', 'Verulam', 'Indian'),
(25, 'Mandla Nkosi', 47, 'Male', 'Nelspruit', 'Black'),
(26, 'Lydia Daniels', 62, 'Female', 'George', 'Coloured'),
(27, 'Brian O''Connor', 39, 'Male', 'Claremont', 'White'),
(28, 'Sibongile Hadebe', 28, 'Female', 'Secunda', 'Black'),
(29, 'Imran Khan', 22, 'Male', 'Laudium', 'Indian'),
(30, 'Hendrik Pretorius', 49, 'Male', 'Kimberley', 'White'),
(31, 'Nomvula Gumede', 36, 'Female', 'Ulundi', 'Black'),
(32, 'Wayne Petersen', 31, 'Male', 'Bellville', 'Coloured'),
(33, 'Tumi Morake', 24, 'Female', 'Rustenburg', 'Black'),
(34, 'Faisal Ismail', 43, 'Male', 'Actonville', 'Indian'),
(35, 'Elsabe Smit', 65, 'Female', 'Welkom', 'White'),
(36, 'Themba Zwane', 29, 'Male', 'Soweto', 'Black'),
(37, 'Alicia Fortuin', 21, 'Female', 'Elsies River', 'Coloured'),
(38, 'Joseph Nkuna', 53, 'Male', 'Giyani', 'Black'),
(39, 'Farah Jacobs', 30, 'Female', 'Athlone', 'Coloured'),
(40, 'Gert Visser', 44, 'Male', 'Potchefstroom', 'White'),
(41, 'Precious Mahlangu', 19, 'Female', 'Daveyton', 'Black'),
(42, 'Nazeem Cassim', 51, 'Male', 'Fordsburg', 'Indian'),
(43, 'Lungile Buthelezi', 27, 'Male', 'KwaDukuza', 'Black'),
(44, 'Janine Cloete', 38, 'Female', 'Kuils River', 'Coloured'),
(45, 'Sello Ramaphosa', 59, 'Male', 'Lebowakgomo', 'Black'),
(46, 'Yusuf Desai', 33, 'Male', 'Azaadville', 'Indian'),
(47, 'Megan van Wyk', 23, 'Female', 'Somerset West', 'Coloured'),
(48, 'Bongani Hlongwane', 41, 'Male', 'Eshowe', 'Black'),
(49, 'Kevin Naude', 46, 'Male', 'Upington', 'White'),
(50, 'Zinhle Madlala', 28, 'Female', 'Umlazi', 'Black');